### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Shinodari** [Shinodari/Warehouse-IO#1]
Conversation about authentication package (authentication branch)

**Comment by Shinodari** [comment]
Department Class ใน Model Package #2 อนุโลมภายใต้ authentication branch

**Comment by Hibino02** [comment]
สร้าง Class Log In และ User
พบสิ่งที่ไม่ตรงตาม Class Diagram
1.ไม่สามารถ update Field หรือ Property ได้ เนื่องจากไม่มี Method รองรับ จึงทำการเพิ่ม Method UpdateUserDetails()
2.ChangePassword() ไม่สามารถทำเป็นรูปแบบ static ได้ เนื่องจาก Object ที่เกี่ยวข้องภายใน Method จะต้องประกาศเป็นรูปแบบ static ตามไปด้วย ดังนี้

- Method: EncryptPassword()
- Field: password
- field: id
- Global variable: connection_string

commit ref : https://github.com/Shinodari/Warehouse-IO/commit/08de0de927cc94e92033e379f0e77ea71d2b4a24

**Comment by Hibino02** [comment]
แก้ใข Concept Setter จากเดิมคือ อัฟเดทลง Database เป็น Update ไปที่ Field commit ref # 5980d03
