### ISSUE TITLE
Department style

### ISSUE THREAD

**Issue by Shinodari** [Shinodari/Warehouse-IO#5]
## Issue about department style
style seem invalid and want something 
> this issue is prototype for similar form

**Comment by Shinodari** [comment]
ตามความเห็นผมนะครับ
1. ใน Department List ควรเรียงลำดับตาม ID
2. **Add, Edit** เปลี่ยนจาก UserControl เป็น DialogBox([Simple](https://github.com/Shinodari/Warehouse-IO-Analysis/blob/c187bf1afe72c4cbbd247411d62a9e01a89a78be/UI/Dialog%20Simple.gif))  ได้ไหม?
    > มันไม่ตรงวัตถุประสงค์ของ componant มันใช่คู่กับ Panel 
    > ถามว่าใช่ได้ไหม? (Login ให้ใช้ได้ เพราะไม่น่าไม่อะไรมาก)
    > ตอบว่าได้ แต่หากมีการแก้ไขในอนาตค อาจเกิดปัญหา

    > หลัง user ป้อนข้อมูล user สามารถกด enter เสมือน user กด ok ได้เลย
    > (ข้อนี้ DialogBox ทำได้ง่ายมาก ไม่ต้องเขียน code)
3. **Remove** เปลี่ยนจาก UserControl เป็น MessageBox ธรรมดาเลยไม่ต้องมีอะไร
    > Concept ประมาณว่า "ถาม User เฉยๆ"
4. **ทั้ง Add, Edit และ Remove
    > หลังจาก Success End Condition หน้าต่าง DialogBox ต้องหายไป ไป Focus ที่ Form หลัก

โดยรวมยังไม่ตรงกับ [Usecase](https://github.com/Shinodari/Warehouse-IO-Analysis/blob/c187bf1afe72c4cbbd247411d62a9e01a89a78be/Usecase%20Description.docx) นะครับ

**Comment by Hibino02** [comment]
> ตามความเห็นผมนะครับ
> 
> 1. ใน Department List ควรเรียงลำดับตาม ID
> 2. **Add, Edit** เปลี่ยนจาก UserControl เป็น DialogBox([Simple](https://github.com/Shinodari/Warehouse-IO-Analysis/blob/c187bf1afe72c4cbbd247411d62a9e01a89a78be/UI/Dialog%20Simple.gif))  ได้ไหม?
>    > มันไม่ตรงวัตถุประสงค์ของ componant มันใช่คู่กับ Panel
>    > ถามว่าใช่ได้ไหม? (Login ให้ใช้ได้ เพราะไม่น่าไม่อะไรมาก)
>    > ตอบว่าได้ แต่หากมีการแก้ไขในอนาตค อาจเกิดปัญหา
>    
>    
>    > หลัง user ป้อนข้อมูล user สามารถกด enter เสมือน user กด ok ได้เลย
>    > (ข้อนี้ DialogBox ทำได้ง่ายมาก ไม่ต้องเขียน code)
> 3. **Remove** เปลี่ยนจาก UserControl เป็น MessageBox ธรรมดาเลยไม่ต้องมีอะไร
>    > Concept ประมาณว่า "ถาม User เฉยๆ"
> 4. **ทั้ง Add, Edit และ Remove
>    > หลังจาก Success End Condition หน้าต่าง DialogBox ต้องหายไป ไป Focus ที่ Form หลัก
> 
> โดยรวมยังไม่ตรงกับ [Usecase](https://github.com/Shinodari/Warehouse-IO-Analysis/blob/c187bf1afe72c4cbbd247411d62a9e01a89a78be/Usecase%20Description.docx) นะครับ

แก้ใขตามที่ร้องขอ ref : https://github.com/Shinodari/Warehouse-IO/commit/1b423ed05ac1509d98eca2e30579efa3934e62ff

**Comment by Shinodari** [comment]
style และ size ของ add และ edit DialogBox ของเป็นประมาณนี้ได้ไหม
![StandardAddEditDialogBox](https://github.com/Shinodari/Warehouse-IO-Analysis/blob/main/UI/StandardAddEditDialogBox.png?raw=true)

**Comment by Hibino02** [comment]
ดำเนินการได้เลย

**Comment by Shinodari** [comment]
อยากให้ issue #5 นี้เป็นต้นแบบไป form และ dialogbox อื่นๆด้วย 
เบื้องต้นที่พบ Add/Edit DialogBox ไม่เป็นไปตามดังภาพ(ใกล้เคียง)
![StandardAddEditDialogBox](https://github.com/Shinodari/Warehouse-IO-Analysis/blob/main/UI/StandardAddEditDialogBox.png?raw=true)
- Departmant Form
- Storage Form
- Suplier Form
- Unit of Volume Form
- Unit of Weight Form
- Packing Form

**Comment by Shinodari** [comment]
ไปต่อที่ Issue #6 นะครับ
